import {
  mulberry32,
  renderCannonBoom,
  renderMusketPop,
  renderNoiseBed,
} from "@/lib/audio/battlefieldAudio";

/**
 * The renderers only need sampleRate and createBuffer, so they can be checked
 * without Web Audio. Everything the site plays is generated by these three
 * functions — there are no audio files to fall back on.
 */
function stubContext(sampleRate = 44100): BaseAudioContext {
  return {
    sampleRate,
    createBuffer(channels: number, length: number, rate: number) {
      const data = new Float32Array(length);
      return {
        length,
        sampleRate: rate,
        numberOfChannels: channels,
        duration: length / rate,
        getChannelData: () => data,
      };
    },
  } as unknown as BaseAudioContext;
}

function rms(data: Float32Array, from: number, to: number): number {
  let total = 0;
  for (let index = from; index < to; index += 1) {
    total += data[index] ** 2;
  }
  return Math.sqrt(total / Math.max(1, to - from));
}

describe("procedural battlefield audio", () => {
  it("renders a musket crack that is loud at the front and gone at the back", () => {
    const context = stubContext();
    const buffer = renderMusketPop(context, mulberry32(1));
    const data = buffer.getChannelData(0);

    const head = rms(data, 0, Math.floor(data.length * 0.1));
    const tail = rms(data, Math.floor(data.length * 0.85), data.length);

    expect(head).toBeGreaterThan(0.02);
    expect(tail).toBeLessThan(head * 0.1);
    expect(Math.max(...data)).toBeLessThanOrEqual(1.6);
  });

  it("renders a gun with a long tail behind the blast", () => {
    const context = stubContext();
    const buffer = renderCannonBoom(context, mulberry32(2));
    const data = buffer.getChannelData(0);

    const blast = rms(data, 0, Math.floor(data.length * 0.05));
    const tail = rms(data, Math.floor(data.length * 0.4), Math.floor(data.length * 0.6));

    expect(buffer.duration).toBeGreaterThan(1.5);
    expect(blast).toBeGreaterThan(0.05);
    // Still ringing at the midpoint, which a musket is not.
    expect(tail).toBeGreaterThan(0.0005);
  });

  it("renders a noise bed whose loop seam does not click", () => {
    const context = stubContext();
    const buffer = renderNoiseBed(context, mulberry32(3));
    const data = buffer.getChannelData(0);

    const seamJump = Math.abs(data[data.length - 1] - data[0]);
    const typicalStep = rms(
      Float32Array.from({ length: 500 }, (_unused, index) => data[index + 1] - data[index]),
      0,
      500,
    );

    expect(seamJump).toBeLessThan(typicalStep * 40);
    expect(rms(data, 0, data.length)).toBeGreaterThan(0.01);
  });

  it("gives the same field for the same seed", () => {
    const first = renderMusketPop(stubContext(), mulberry32(7)).getChannelData(0);
    const second = renderMusketPop(stubContext(), mulberry32(7)).getChannelData(0);
    expect(Array.from(first.slice(0, 40))).toEqual(Array.from(second.slice(0, 40)));
  });
});
